openapi: 3.0.4
info:
  title: Personal Library Manager
  description: An API to manage a personal library of books.
  version: 1.0.0

paths:
  /books:
    get:
      summary: List all books
      description: Retrieves a list of all books in the library.
      responses:
        "200":
          description: List of books successfully retrieved.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
    post:
      summary: Add a new book
      description: Adds a new book to the library.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Book"
      responses:
        "201":
          description: Book successfully added.

  /books/{id}:
    get:
      summary: Retrieve a book
      description: Retrieves the details of a specific book.
      parameters:
        - name: id
          in: path
          required: true
          description: Book ID
          schema:
            type: string
      responses:
        "200":
          description: Book details successfully retrieved.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
        "404":
          description: Book not found.
    put:
      summary: Update a book
      description: Updates the information of a specific book.
      parameters:
        - name: id
          in: path
          required: true
          description: Book ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Book"
      responses:
          description: Book successfully updated.
        "404":
          description: Book not found.
      delete:
        summary: Delete a book
        description: Deletes a specific book from the library.
        parameters:
        - name: id
          in: path
          required: true
          description: Book ID
          schema:
          type: string
        responses:
        "204":
          description: Book successfully deleted.
        "404":
          description: Book not found.

    components:
      schemas:
      Book:
        type: object
        properties:
        id:
          type: string
          description: Unique ID of the book.
        title:
          type: string
          description: Title of the book.
        author:
          type: string
          description: Author of the book.
        publicationDate:
          type: string
          format: date
          description: Publication date of the book.
        summary:
          type: string
          description: Summary of the book.
        required:
        - id
        - title
        - author
